version: "3.9"

services:
  web:
    build: .
    command: python /energy_api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/energy_api
    environment:
      POSTGRES_HOST: db
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
       POSTGRES_DB: energy_api
       POSTGRES_USER: energy_api_user
       POSTGRES_PASSWORD: energy_api_password

volumes:
  postgres_data:


