# Generated by Django 4.0.6 on 2022-07-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('energy_type', models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('measurement', models.DecimalField(decimal_places=4, help_text='energy in MW(Mega Watts)', max_digits=25)),
                ('energy_park', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='park', to='core.energypark')),
            ],
        ),
    ]
